import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import { Inter } from "next/font/google";
import RouterMounting from "@/app/shared/RouterMounting";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RouterMounting>{children}</RouterMounting>
      </body>
    </html>
  );
}
